version: '3'
services:
  mongodb:
    image: mongo:latest
    container_name: devflow_mongo
    volumes:
      - mongodb:/data/db
      - mongodb_config:/data/configdb
    networks:
      - devflow
  devflow:
    build:
      dockerfile: ./development.dockerfile
      context: .
    image: terrakrya/devflow
    container_name: devflow_node
    command: npm run dev
    ports:
      - '3000:3000'
    volumes:
      - ../:/devflow
    networks:
      - devflow
    depends_on:
      - 'mongodb'

networks:
  devflow:
    driver: bridge
volumes:
  mongodb:
  mongodb_config:
