name: Deploy Production

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: deploy_stage
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: 'source ~/.nvm/nvm.sh; cd ~/server/; ./update.sh; ./deploy.sh dev-flow; exit'
          host: prod-sites.terrakrya.com
          username: root
          privateKey: ${{ secrets.SSH_PRIVATE_KEY }}
